### PR TITLE
Wiki -> Documentation Folder

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>

Please check the **[Preview]**

<br>

### Changes

- Moved wiki files into `Documentation` folder
- Moved images to `Resources/Image`
- Formatted / Renamed files
- Fixed paths
- Added linked banners
- Removed empty files

#### Files Remaining ` 3 `

[Preview]: https://github.com/ElectronicsArchiver/EncoderTool/tree/Documentation

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
God damn Arduino filesystem bs again..

Well how about this, for the current PR I change 
it back to how it was before and in a subsequent 
PR the library gets moved into a folder by itself, 
something like `Library`?

You have to upload the files to the Arduino Library Registry, 
so it wouldn't be a problem right? Or does it use a link, in 
which case it should still be possible?

**Comment by luni64** [comment]
I copied the current landing page from the main branch to the PR.

**Comment by ElectronicsArchiver** [comment]
Huh? Why would you do that?

**Comment by luni64** [comment]
> God damn Arduino filesystem bs again..
> 
> Well how about this, for the current PR I change it back to how it was before and in a subsequent PR the library gets moved into a folder by itself, something like `Library`?
> 
> You have to upload the files to the Arduino Library Registry, so it wouldn't be a problem right? Or does it use a link, in which case it should still be possible?

Nope, that won't work the structure is quite strict otherwise the library manager will refuse to load it.  So it needs to be compliant to the 1.5 library spec

**Comment by luni64** [comment]
> Huh? Why would you do that?

No worries, not the original one but the one from you which I worked on the last days.  It has active badges now and I fixed the content. Need to fix the links to the document folder (still point to the wiki) but this can be done later

**Comment by ElectronicsArchiver** [comment]
> Nope, that won't work the structure is quite strict otherwise the library manager will refuse to load it. So it needs to be compliant to the 1.5 library spec

You cannot just use a folder which the `library.properties` and `library.json` files in them?

**Comment by luni64** [comment]
> You cannot just use a folder which the `library.properties` and `library.json` files in them?

No, the Arduino builder relies on it here again the spec:  https://arduino.github.io/arduino-cli/0.21/library-specification/.  But actually this is not a big thing as long as it works

**Comment by luni64** [comment]
I had a closer look by now. Some comments
- I really like the colorful overview.md page.  Gives it a fresh look and animates to read into it, well done...
- You also did very good work in simplifying some of my complicated explanations :-).
- I'm not sure if the banner should be on all pages? Looks a bit overloaded to me.  
- You manually added hard line breaks. Are you sure that this is a good ideay? On small displays this generates jagged text, on large displays it looks somehow strange. 

All in all I like it very much. Looking forward to publish it.

**Comment by ElectronicsArchiver** [comment]
About manual line breaks:
Often people argue that it breaks it for mobile, but forget that most of the people using GitHub are on Desktop.
So by not properly formatting text and "leaving it up to the page" it will just go from left to right on basically any slightly modern screen.
People also forget what a typesetters job is, that is, setting text to be readable.
60 characters per line would be ideal, just like in books and newspaper articles, as that is literally the average human limit, more just makes you switch from left to right and disorients the reader.
I usually go with 60-80 for a better acceptance rate, its hard to get some people to even < 100 ..
If you really care about mobile, I would suggest the same as someone that really cares about multi-language support, make a separate adjusted version.

About the banner:
I added it for two reasons, as a link back to the overview, like logos usually link back to a home page and to theme the documentation to the repositories topic.
I could make the banner thinner if you'd like~

**Comment by luni64** [comment]
> 60 characters per line would be ideal, just like in books and newspaper articles, as that is literally the average human limit, more just makes you switch from left to right and disorients the reader.
I usually go with 60-80 for a better acceptance rate, its hard to get some people to even < 100 ..

Agreed,  your design, you decide.

> If you really care about mobile, I would suggest the same as someone that really cares about multi-language support, make a separate adjusted version.

Is this even possible with a github markdown file? Anyway, I'm fine with the 60 

> I could make the banner thinner if you'd like~

Can you give it a try on one of the pages? (if it doesn't generate too much work of course)

**Comment by ElectronicsArchiver** [comment]
> Is this even possible with a github markdown file? Anyway, I'm fine with the 60

Like with different lang documentation it would be separate and 
usually linked to with a header bar containing a language selection.

*If you use GitHub pages, you can of course build that in.*

> Can you give it a try on one of the pages? (if it doesn't generate too much work of course)

Sure~

**Comment by ElectronicsArchiver** [comment]
[Overview]

[Overview]: https://github.com/ElectronicsArchiver/EncoderTool/blob/Documentation/Documentation/Overview.md

**Comment by luni64** [comment]
Wow, this is really nice. Thanks a lot for all the work. Would you mind placing something like "design by ElectronicsArchiver"  on the pages? Honour where honour is due...

**Comment by ElectronicsArchiver** [comment]
Thanks.

Well I could add a contributors page, if you don't mind that~

**Comment by luni64** [comment]
Thats a good idea. You could also mention @ihatemornings  who did the 4051 extenison

**Comment by luni64** [comment]
lunOptics is just me from a test account

**Comment by luni64** [comment]
So, I'll pull it into master then

**Pull request merged**
